version: 2

project_name: goodhosts

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: macos
    goos:
      - darwin
    main: ./cmd/goodhosts/main.go
    binary: goodhosts
    ldflags:
      - -s -w -X github.com/ChrisWiegman/goodhosts/internal/cmd.Version={{.Version}} -X github.com/ChrisWiegman/goodhosts/internal/cmd.Timestamp={{.Date}}
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/goodhosts/main.go
    binary: goodhosts
    ldflags:
      - -s -w -X github.com/ChrisWiegman/goodhosts/internal/cmd.Version={{.Version}} -X github.com/ChrisWiegman/goodhosts/internal/cmd.Timestamp={{.Date}}

archives:
  - id: macos
    ids:
      - macos
      - linux
    formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE.txt
      - CHANGELOG.md

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

changelog:
  disable: false

nfpms:
  - vendor: Chris Wiegman
    ids:
      - linux
    license: MIT license
    homepage: https://github.com/ChrisWiegman/goodhosts
    maintainer: Chris Wiegman <contact@chriswiegman.com>
    description: A utility for editing your hosts file with single entries or blocks of entries.
    file_name_template: >-
      {{ .ProjectName }}_
      {{-  .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - apk
      - deb
      - rpm
      - archlinux

brews:
  - repository:
      owner: ChrisWiegman
      name: homebrew-goodhosts
      branch: main
    name: goodhosts
    license: MIT license
    test: |
      system "#{bin}/goodhosts version"
    homepage: https://github.com/ChrisWiegman/goodhosts
    description: A utility for editing your hosts file with single entries or blocks of entries.
