project_name: goodhosts

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: macos
    goos:
      - darwin
    main: ./cmd/goodhosts/main.go
    binary: goodhosts
    ldflags:
      - -s -w -X github.com/ChrisWiegman/goodhosts/v4/internal/commands.Version={{.Version}} -X github.com/ChrisWiegman/goodhosts/v4/internal/commands.Timestamp={{.Date}}
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/goodhosts/main.go
    binary: goodhosts
    ldflags:
      - -s -w -X github.com/ChrisWiegman/goodhosts/v4/internal/commands.Version={{.Version}} -X github.com/ChrisWiegman/goodhosts/v4/internal/commands.Timestamp={{.Date}}

archives:
  - id: macos
    builds:
      - macos
      - linux
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
      darwin: macos
    files:
      - LICENSE.txt
      - CHANGELOG.md

snapshot:
  name_template: "{{ incpatch .Version }}-devel"

changelog:
  skip: false

nfpms:
  - vendor: Chris Wiegman
    builds:
      - linux
    license: MIT license
    homepage: https://github.com/ChrisWiegman/goodhosts
    maintainer: Chris Wiegman <contact@chriswiegman.com>
    description: A utility for editing your hosts file with single entries or blocks of entries.
    replacements:
      amd64: x86_64
    formats:
      - apk
      - deb
      - rpm
      - archlinux

brews:
  - tap:
      owner: ChrisWiegman
      name: homebrew-goodhosts
      branch: main
    name: goodhosts
    license: MIT license
    test: |
      system "#{bin}/goodhosts version"
    homepage: https://github.com/ChrisWiegman/goodhosts
    description: A utility for editing your hosts file with single entries or blocks of entries.
