name: Tests

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Linting
        run: |
          make test-lint
      - name: Unit Testing
        run: |
          make test-unit
